# Generated by Django 3.1 on 2020-08-09 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=200, null=True)),
                ('orgemail', models.CharField(max_length=200, null=True)),
                ('orgcontact', models.CharField(max_length=200, null=True)),
                ('orgaddress', models.CharField(max_length=200, null=True)),
                ('orglicense', models.CharField(max_length=200, null=True)),
                ('orgdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('organization_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.organization')),
            ],
        ),
    ]
